/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SuhuForm extends javax.swing.JFrame {

    /**
     * Creates new form SuhuForm
     */
    public SuhuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 147, 186));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Input Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Pilih Suhu Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Pilih Suhu Kedua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Hasil Konversi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(238, 175, 217));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jTextField1, gridBagConstraints);

        jComboBox1.setBackground(new java.awt.Color(238, 175, 217));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(238, 175, 217));
        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jButton1, gridBagConstraints);

        jRadioButton1.setBackground(new java.awt.Color(238, 175, 217));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Celcius");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setBackground(new java.awt.Color(238, 175, 217));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Fahrenheit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setBackground(new java.awt.Color(238, 175, 217));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Remur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jRadioButton3, gridBagConstraints);

        jRadioButton4.setBackground(new java.awt.Color(238, 175, 217));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Kelvin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jRadioButton4, gridBagConstraints);

        jTextField2.setBackground(new java.awt.Color(238, 175, 217));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jTextField2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        double inputSuhu = Double.parseDouble(jTextField1.getText());
        String suhuAwal = "";
        String suhuKonversi = (String) jComboBox1.getSelectedItem();
        double hasilKonversi = 0;
        
        if (jRadioButton1.isSelected()) {
            suhuAwal = "Celcius";
        } else if (jRadioButton2.isSelected()) {
            suhuAwal = "Fahrenheit";
        } else if (jRadioButton3.isSelected()) {
            suhuAwal = "Reamur";
        } else if (jRadioButton4.isSelected()) {
            suhuAwal = "Kelvin";
        }

        if (suhuAwal.equals("Celcius")) {
            if (suhuKonversi.equals("Fahrenheit")) {
                hasilKonversi = (inputSuhu * 9/5) + 32;
            } else if (suhuKonversi.equals("Reamur")) {
                hasilKonversi = inputSuhu * 4/5;
            } else if (suhuKonversi.equals("Kelvin")) {
                hasilKonversi = inputSuhu + 273.15;
            } else {
                hasilKonversi = inputSuhu;
            }
        } else if (suhuAwal.equals("Fahrenheit")) {
            if (suhuKonversi.equals("Celcius")) {
                hasilKonversi = (inputSuhu - 32) * 5/9;
            } else if (suhuKonversi.equals("Reamur")) {
                hasilKonversi = (inputSuhu - 32) * 4/9;
            } else if (suhuKonversi.equals("Kelvin")) {
                hasilKonversi = (inputSuhu - 32) * 5/9 + 273.15;
            } else {
                hasilKonversi = inputSuhu;
            }
        } else if (suhuAwal.equals("Reamur")) {
            if (suhuKonversi.equals("Celcius")) {
                hasilKonversi = inputSuhu * 5/4;
            } else if (suhuKonversi.equals("Fahrenheit")) {
                hasilKonversi = (inputSuhu * 9/4) + 32;
            } else if (suhuKonversi.equals("Kelvin")) {
                hasilKonversi = inputSuhu * 5/4 + 273.15;
            } else {
                hasilKonversi = inputSuhu;
            }
        } else if (suhuAwal.equals("Kelvin")) {
            if (suhuKonversi.equals("Celcius")) {
                hasilKonversi = inputSuhu - 273.15;
            } else if (suhuKonversi.equals("Fahrenheit")) {
                hasilKonversi = (inputSuhu - 273.15) * 9/5 + 32;
            } else if (suhuKonversi.equals("Reamur")) {
                hasilKonversi = (inputSuhu - 273.15) * 4/5;
            } else {
                hasilKonversi = inputSuhu;
            } 
        }

        jTextField2.setText(String.format("%.2f", hasilKonversi));
    } catch (NumberFormatException e) {
        jTextField2.setText("Invalid input!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuhuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuhuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
